spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: root
    password: 
  h2:
    console:
      path: /h2-console
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
server:
  port: 10521
wx:
  appId: #填写你自己的小程序appId
  secret: #填写你自己的小程序secret
logging:
  file:
    name: toolApi.log


